name: Publicar página en Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Puedes ajustar la versión según tus necesidades

      - name: Instalar Surge
        run: npm install --global surge
        
      - name: Publicar página
        run: surge --project ./ --domain ${{secrets.SURGE_DOMAIN}} --token ${{ secrets.SURGE_API_KEY }}
